services:
  web:
    build: .
    container_name: booklog-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: booklog-db
    environment:
      POSTGRES_DB: booklog
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: